version: '3'

services:
  # Backend Services
  auth-service:
    build: ./packages/backend/auth-service
    image: auth-service
    container_name: auth-service
    restart: unless-stopped
    environment:
      - PORT=4001
      - AMQP_HOST=host.docker.internal
      - QUEUE_NAME=test-queue
    ports:
      - '4001:4001'
    volumes:
      - ./packages/backend/auth-service:/usr/app
      - ./packages/backend/auth-service/node_modules:/usr/app/node_modules
    networks:
      - student-loan-network
  db-service:
    build: ./packages/backend/db-service
    image: db-service
    container_name: db-service
    restart: unless-stopped
    environment:
      - PORT=4002
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DB=studentLoanDB
      - AMQP_HOST=host.docker.internal
      - QUEUE_NAME=test-queue
    ports:
      - '4002:4002'
    volumes:
      - ./packages/backend/db-service:/usr/app
      - ./packages/backend/db-service/node_modules:/usr/app/node_modules
    networks:
      - student-loan-network
  # Auxiliary Services
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    environment: {}
    volumes:
      - dbdata:/data/db
    networks:
      - student-loan-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment: {}
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
      - rabbitmqlogs:/var/log/rabbitmq
    networks:
      - student-loan-network
networks:
  student-loan-network:
    driver: bridge

volumes:
  dbdata: {}
  node_modules: {}
  rabbitmqdata: {}
  rabbitmqlogs: {}
